require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe Admin::ServicePackagesController do

  render_views

  def mock_service_package(stubs={})
    @mock_service_package ||= mock_model(ServicePackage, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all service_packages as @service_packages" do
      ServicePackage.stub(:all) { [mock_service_package] }
      get :index
      assigns(:service_packages).should eq([mock_service_package])
    end
  end

  describe "GET show" do
    it "assigns the requested service_package as @service_package" do
      ServicePackage.stub(:find).with("37") { mock_service_package }
      get :show, :id => "37"
      assigns(:service_package).should be(mock_service_package)
    end
  end

  describe "GET new" do
    it "assigns a new service_package as @service_package" do
      ServicePackage.stub(:new) { mock_service_package }
      get :new
      assigns(:service_package).should be(mock_service_package)
    end
  end

  describe "GET edit" do
    it "assigns the requested service_package as @service_package" do
      ServicePackage.stub(:find).with("37") { mock_service_package }
      get :edit, :id => "37"
      assigns(:service_package).should be(mock_service_package)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created service_package as @service_package" do
        ServicePackage.stub(:new).with({'these' => 'params'}) { mock_service_package(:save => true) }
        post :create, :service_package => {'these' => 'params'}
        assigns(:service_package).should be(mock_service_package)
      end

      it "redirects to the created service_package" do
        ServicePackage.stub(:new) { mock_service_package(:save => true) }
        post :create, :service_package => {}
        response.should redirect_to(service_package_url(mock_service_package))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved service_package as @service_package" do
        ServicePackage.stub(:new).with({'these' => 'params'}) { mock_service_package(:save => false) }
        post :create, :service_package => {'these' => 'params'}
        assigns(:service_package).should be(mock_service_package)
      end

      it "re-renders the 'new' template" do
        ServicePackage.stub(:new) { mock_service_package(:save => false) }
        post :create, :service_package => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested service_package" do
        ServicePackage.stub(:find).with("37") { mock_service_package }
        mock_service_package.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :service_package => {'these' => 'params'}
      end

      it "assigns the requested service_package as @service_package" do
        ServicePackage.stub(:find) { mock_service_package(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:service_package).should be(mock_service_package)
      end

      it "redirects to the service_package" do
        ServicePackage.stub(:find) { mock_service_package(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(service_package_url(mock_service_package))
      end
    end

    describe "with invalid params" do
      it "assigns the service_package as @service_package" do
        ServicePackage.stub(:find) { mock_service_package(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:service_package).should be(mock_service_package)
      end

      it "re-renders the 'edit' template" do
        ServicePackage.stub(:find) { mock_service_package(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested service_package" do
      ServicePackage.stub(:find).with("37") { mock_service_package }
      mock_service_package.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the service_packages list" do
      ServicePackage.stub(:find) { mock_service_package }
      delete :destroy, :id => "1"
      response.should redirect_to(service_packages_url)
    end
  end

end
