require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MobileServicesController do

  #render_views
  
  def mock_mobile_service(stubs={})
    @mock_mobile_service ||= mock_model(MobileService, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all mobile_services as @mobile_services" do
      MobileService.stub(:all) { [mock_mobile_service] }
      get :index
      assigns(:mobile_services).should eq([mock_mobile_service])
    end
  end

  describe "GET show" do
    it "assigns the requested mobile_service as @mobile_service" do
      MobileService.stub(:find).with("37") { mock_mobile_service }
      get :show, :id => "37"
      assigns(:mobile_service).should be(mock_mobile_service)
    end
  end

end
