require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MobileServicesController do

  #render_views
  
  describe "GET index" do
    it "assigns all mobile_services as @mobile_services" do
      ms = MobileService.make!
      get :index
      assigns(:mobile_services).should == [ms]
    end
  end

  describe "GET show by id" do
    it "assigns the requested mobile_service as @mobile_service" do
      ms = MobileService.make!
      get :show, :id => ms.id.to_s
      assigns(:mobile_service).should == ms
    end
  end

  describe "GET show by urltitle" do
    it "assigns the requested mobile_service as @mobile_service" do
      ms = MobileService.make!
      get :show, :id => ms.urltitle
      assigns(:mobile_service).should == ms
    end
  end

end
