require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ServicePackagesController do

  render_views

  def mock_service_package(stubs={})
    @mock_service_package ||= mock_model(ServicePackage, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all service_packages as @service_packages" do
      ServicePackage.stub(:all) { [mock_service_package] }
      get :index
      assigns(:service_packages).should eq([mock_service_package])
    end
  end

  describe "GET show" do
    it "assigns the requested service_package as @service_package" do
      ServicePackage.stub(:find).with("37") { mock_service_package }
      get :show, :id => "37"
      assigns(:service_package).should be(mock_service_package)
    end
  end

end
