require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ServicePackagesController do

  #render_views

  describe "GET index" do
    it "assigns all service_packages as @service_packages" do
      splist = ServicePackage.make!(2)
      get :index
      assigns(:service_packages).should == splist
    end
  end

  describe "GET show by id" do
    it "assigns the requested service_package as @service_package" do
      sp = ServicePackage.make!
      get :show, :id => sp.id.to_s
      assigns(:service_package).should == sp
    end
  end

  describe "GET show by urlname" do
    it "assigns the requested service_package as @service_package" do
      sp = ServicePackage.make!
      get :show, :id => sp.urlname
      assigns(:service_package).should == sp
    end
  end

end
